<div class="jumbotron">
    <h1>Chào mừng đến với <span class="zf-green">Zend Form</span></h1>

    <p>
        Đây là code ứng dụng ví dụ về sử dụng Zend Form, thông tin chi tiết tại
        <a href="https://xuanthulab.net/cai-dat-zend-framework-chuong-trinh-dau-tien.html" target="_blank">Lập trình ZF</a>.
        Thư viện hiện tại đang dùng là <?= \Application\Module::VERSION ?>.


    </p>
    <p>
        <a class="btn btn-sm btn-warning" href="<?=$this->url('home')?>contact/contactone">Liên hệ 1</a>
        <a class="btn btn-sm btn-warning" href="<?=$this->url('home')?>contact/contacttwo">Liên hệ 2</a>
        <a class="btn btn-sm btn-warning" href="<?=$this->url('home')?>contact/contactthree">Liên hệ 3</a>
        <a class="btn btn-sm btn-warning" href="<?=$this->url('home')?>contact/contactfour">Liên hệ 4</a>
        <a class="btn btn-sm btn-warning" href="<?=$this->url('home')?>contact/contactfive">Liên hệ 5</a>
        <a class="btn btn-sm btn-warning" href="<?=$this->url('home')?>contact/contactsix">Liên hệ 6</a>
        <a class="btn btn-sm btn-warning" href="<?=$this->url('home')?>contact/contactseven">Liên hệ 7</a>
        <a class="btn btn-sm btn-warning" href="<?=$this->url('home')?>contact/contacteight">Liên hệ 8</a>

    </p>

    <p><a class="btn btn-success btn-lg" href="https://xuanthulab.net/" target="_blank">Hướng dẫn lập trình PHP &raquo;</a></p>
</div>