<div class="jumbotron">
    <h1>Chào mừng đến với <span class="zf-green">ZF</span></h1>

    <p>
        Học về
        <a href="https://xuanthulab.net/cai-dat-zend-framework-chuong-trinh-dau-tien.html" target="_blank">Lập trình ZF</a>.
        Thư viện hiện tại đang dùng là <?= \Application\Module::VERSION ?>.


    </p>


    <p><a class="btn btn-success btn-lg" href="https://xuanthulab.net/" target="_blank">Hướng dẫn lập trình PHP Zend Framework &raquo;</a></p>
</div>
